"""
report_generator.py

Generates CSV and PDF incident reports for the
Log File Analyzer for Intrusion Detection project.
"""

import os
import pandas as pd
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors


class ReportGenerator:

    def __init__(self, output_dir="reports"):

        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

  
    # CSV REPORT


    def generate_csv(self,
                     brute_force,
                     dos,
                     port_scan):

        frames = []

        if not brute_force.empty:
            brute_force = brute_force.copy()
            brute_force["Attack Type"] = "Brute Force"
            frames.append(brute_force)

        if not dos.empty:
            dos = dos.copy()
            dos["Attack Type"] = "DoS"
            frames.append(dos)

        if not port_scan.empty:
            port_scan = port_scan.copy()
            port_scan["Attack Type"] = "Port Scan"
            frames.append(port_scan)

        if len(frames) == 0:
            print("No attacks detected.")
            return

        report = pd.concat(frames)

        filename = os.path.join(
            self.output_dir,
            "incident_report.csv"
        )

        report.to_csv(filename, index=False)

        print(f"CSV Report Saved: {filename}")


    # PDF REPORT
   

    def generate_pdf(self, summary):

        filename = os.path.join(
            self.output_dir,
            "incident_report.pdf"
        )

        document = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        story = []

        story.append(
            Paragraph(
                "Log File Analyzer Report",
                styles["Title"]
            )
        )

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                "<b>Summary</b>",
                styles["Heading2"]
            )
        )

        table_data = [

            ["Metric", "Value"],

            ["Apache Requests",
             summary["apache_requests"]],

            ["SSH Attempts",
             summary["ssh_attempts"]],

            ["Brute Force",
             summary["brute_force"]],

            ["DoS",
             summary["dos"]],

            ["Port Scan",
             summary["port_scan"]],

            ["Threat Score",
             summary["threat_score"]],

            ["Threat Level",
             summary["threat_level"]]

        ]

        table = Table(table_data)

        table.setStyle(

            TableStyle([

                ("BACKGROUND",
                 (0, 0),
                 (-1, 0),
                 colors.darkblue),

                ("TEXTCOLOR",
                 (0, 0),
                 (-1, 0),
                 colors.white),

                ("GRID",
                 (0, 0),
                 (-1, -1),
                 1,
                 colors.black),

                ("BACKGROUND",
                 (0, 1),
                 (-1, -1),
                 colors.beige),

                ("ALIGN",
                 (0, 0),
                 (-1, -1),
                 "CENTER")

            ])

        )

        story.append(table)

        story.append(Spacer(1, 20))

        story.append(

            Paragraph(

                """
                This report was automatically generated by the
                Log File Analyzer for Intrusion Detection.
                The tool analyzes Apache and SSH logs,
                detects suspicious activities,
                and summarizes security events.
                """,

                styles["BodyText"]

            )

        )

        document.build(story)

        print(f"PDF Report Saved: {filename}")

  
    # FULL REPORT


    def generate_all(self,
                     brute_force,
                     dos,
                     port_scan,
                     summary):

        self.generate_csv(
            brute_force,
            dos,
            port_scan
        )

        self.generate_pdf(summary)


# Testing


if __name__ == "__main__":

    generator = ReportGenerator()

    sample_summary = {

        "apache_requests": 1200,
        "ssh_attempts": 250,
        "brute_force": 5,
        "dos": 2,
        "port_scan": 3,
        "threat_score": 48,
        "threat_level": "HIGH"

    }

    brute = pd.DataFrame({

        "ip": ["192.168.1.10"],
        "attempts": [12]

    })

    dos = pd.DataFrame({

        "ip": ["10.0.0.5"],
        "requests": [450]

    })

    scan = pd.DataFrame({

        "ip": ["172.16.1.25"],
        "unique_ports": [35]

    })

    generator.generate_all(
        brute,
        dos,
        scan,
        sample_summary
    )

    print("Reports generated successfully.")
